server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://59.110.219.163:3306/post
    username: root
    password: Zwk5231956!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
security:
  token:
    name: token